### ISSUE TITLE
Prepend <prog> to hrefs but not prepend it in subsections

### ISSUE THREAD

**Issue by mondeja** [gaborbernat/sphinx-argparse-cli#11]
**Is your feature request related to a problem? Please describe.**
~~In [mdpo I've all CLI program references in the same page](https://mdpo.readthedocs.io/en/master/cli.html#-h), so if I click in the link of [`po2md` CLI program reference](fhttps://mdpo.readthedocs.io/en/master/cli.html#po2md), for example [`-h`](https://mdpo.readthedocs.io/en/master/cli.html#-h) argument or [`optional arguments`](https://mdpo.readthedocs.io/en/master/cli.html#optional-arguments) links, they will lead me the wrong way to [`md2po` section](https://mdpo.readthedocs.io/en/master/cli.html#md2po).~~

EDIT: This seems fixed in v1.6.0, but that version prepends the program name to subsections. Could be possible to remove them (words marked in red below)?

![image](https://user-images.githubusercontent.com/23049315/114934186-e22f3080-9e39-11eb-8731-4430b62cffaa.png)

**Describe the solution you'd like**
Remove `<prog>` from subsection titles: instead of `md2po positional arguments` just `positional arguments`. Maybe a configuration option for `conf.py` or a directive, or both? I'm not sure.

**Comment by gaborbernat** [comment]
This should be the case with 1.6.0, is it not?

**Comment by gaborbernat** [comment]
Why do you want to remove it from subsections?

**Comment by mondeja** [comment]
It is mostly because I like that way :sweat_smile: but anyways I think that the parent section title is describing yet what program is and I feel like it is redundant reminding again in arguments subsections.

**Comment by gaborbernat** [comment]
The thing is the parent part (title) can be disabled. And without it you can still have two optional arguments on the same page which makes it a bit confusing🤔

**Comment by mondeja** [comment]
I understand, it is a bit subjective, an implementation for that could have side effecs and could add some strange complexity. I've solved with few lines of Javascript, so feel free to close this :+1:

**Comment by gaborbernat** [comment]
We could add some configuration flags to it just trying to understand the need here 👍

**Comment by mondeja** [comment]
> The thing is the parent part (title) can be disabled. And without it you can still have two optional arguments on the same page which makes it a bit confusing

It would be to remove only the `<prog>` part of the subsection title, but maintain hrefs as is, would be possible or it is too subjective?

**Comment by gaborbernat** [comment]
I think it's possible, I'll try, or feel free to add a pr 👍
