### ISSUE TITLE
Possibility of not including the title

### ISSUE THREAD

**Issue by mondeja** [gaborbernat/sphinx-argparse-cli#2]
Thank you for this utility and the quick feedback, I've only one problem more to use this in in my project.

**Is your feature request related to a problem? Please describe.**
I've this RST structure:

```rst
***********************
Command line interfaces
***********************

foo
===

.. sphinx_argparse_cli::
  :module: foo.__main__
  :func: build_parser
  :prog: foo

bar
===

.. sphinx_argparse_cli::
  :module: bar.__main__
  :func: build_parser
  :prog: bar
```

That is rendered in HTML as:

```html
<h1>Command line interfaces</h1>

<h2>foo</h2>
<h3>foo - CLI Interface</h3>

... Rest of `h3` sections

<h2>bar</h2>
<h3>bar - CLI Interface</h3>

... Rest of `h3` sections
```

**Describe the solution you'd like**
I would like to remove the first `<h3>` rendered by `sphinx_argparse_cli`, so I can specify my own title in an `h2` tag. Something like:

```html
<h1>Command line interfaces</h1>

<h2>foo</h2>

... Rest of `h3` sections

<h2>bar</h2>

... Rest of `h3` sections
```

**Describe alternatives you've considered**
A boolean `include_title` directive, but I'm not sure if this is out of your expectations for this package or if you would like to solve it in another way :thinking:

**Comment by gaborbernat** [comment]
I think having a boolean flag (to include title) by default ``True`` is good option here.
