### ISSUE TITLE
Cross-referencing a subcommand

### ISSUE THREAD

**Issue by rth** [gaborbernat/sphinx-argparse-cli#7]
Thanks for this package!

Is there a way to link to a particular subcommand using [sphinx cross-referencing](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#the-ref-role)?

Say, I have a setup as 

```rst                                                                                                                                                                                          
.. sphinx_argparse_cli::                                                                                                                                                                                 
   :module: mymodule                                                                                                                                                                  
   :func: make_parser                                                                                                                                                                                    
   :prog: my_cli                                                                                                                                                                                    
   :title:                                                                                                                                                                                               
```      

where there are subcommands `cli1` and `cli2`.

Can I link to it with, something like
```py
:ref:`mymodule.make_parser-cli1`
```
?

After a superficial look https://github.com/gaborbernat/sphinx-argparse-cli/blob/2e0b6bbffa78bdf4d4bb7bfc4b250e66a182f1eb/src/sphinx_argparse_cli/_logic.py#L176 could be relevant? I tried different combinations for `:ref:` arguments but I'm probably missing something.

**Comment by gaborbernat** [comment]
It would be the title you'd link to, but I see you've disabled that part 🤔 In this case you'd have to inject your own anchor before the directive to be able to link to it.

**Comment by rth** [comment]
> It would be the title you'd link to, but I see you've disabled that part

Right but the comman title would link to `my_cli`, I assume, while I would like to link to `my_cli cli1`. Similarly I can add an anchor in RST for the main command but not subcommands I think?

To give a more concrete example with https://github.com/pyodide/pyodide/pull/1471, in the rendered docs I would like to link to a [specific subcommand in the generated docs](https://pyodide--1471.org.readthedocs.build/en/1471/usage/api/pyodide-build-cli.html#pyodide-mkpkg). In this example, the anchor for the generated HTML for the subsection is `pyodide-mkpkg`, however
```
:ref:`pyodide-mkpkg`
```
or other variations that I tried don't seem to work.

**Comment by gaborbernat** [comment]
Hmm, I'd expect `` :ref:`mpyodide-mkpk` `` to work 🤔 if not then it's an actually bug somewhere.

**Comment by gaborbernat** [comment]
Fixed by https://github.com/gaborbernat/sphinx-argparse-cli/commit/50a092f42b26084c64573ad7263dfc1f00c57bec

**Comment by gaborbernat** [comment]
Released under https://pypi.org/project/sphinx-argparse-cli/1.6.0/, documentation about it available at https://github.com/gaborbernat/sphinx-argparse-cli#refer-to-generated-content

**Comment by rth** [comment]
Thanks a lot for the fix and for making a new release @gaborbernat !
